# Generated by Django 5.2.3 on 2025-09-30 16:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="default_pfp.jpg",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
