# Generated by Django 5.2.3 on 2025-07-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
