# Generated by Django 5.2.3 on 2025-07-09 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="rsvps",
            field=models.ManyToManyField(
                blank=True, related_name="rsvped_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
