# Generated by Django 5.2.3 on 2025-09-30 16:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="event_images/default.jpg",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
