# Generated by Django 5.2.3 on 2025-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_rsvps"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="event_images/default.jpg",
                null=True,
                upload_to="event_images/",
            ),
        ),
    ]
