# Generated by Django 5.2.3 on 2025-07-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="participants",
        ),
    ]
